# オーナーのメールアドレス（通知用）
owner_email = "sato.koki@keyocokyba.com"

# 保存先フォルダID（このフォルダ内にスプレッドシートが作成されます）
target_folder_id = "1_UBgENfxTV0uQfzkM3QfyjWygmc8RkI5"

[gcp_service_account]
type = "service_account"
project_id = "list-create-tool"
private_key_id = "410a7f0164d33be585da83f414efadc3488dfecd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDb15YM/3Ledglo
G+CiVgqJVQu21O4K3u8PK9GhbK5NioBqyYZjNyxpWe/EfVQh+Gq7kuUrEsZkmX7P
BR7H+KTfqGN15BSlgk7tTztYUrDZOwbIZlg1sbjcPZgKaOQugcmeaw21osDIAaMO
kY0qRhPQROLiWcjKSp1uLY4N/DAVyTO6z16aIGaFUgMae3KrxHcvwQhT6+uciZpU
9n/cEUq5MKFPz5/Gp12qW+EcUWkyZKp0R+iPOy25dEpITh0HBQBV29DVkVcQItFH
VHL9pGA88LC4MXBbHsE73NwgH5Iw02/hObDgr+WzNxOmXS7AUJWnY7lLm1b/a+GL
NXjKZjETAgMBAAECggEAASSFFQxlCUT5EHPrL8zRxzNSPCzFJuF+qpmchiS5SWMp
uPukcOcH4CeUJwEGqzHOK3ywyptXMY1kgiiXSnUoHjnY1WfCt7Y83A5cjWv4m4b8
vcPpsC/wkH3x1EV6BoIKAchU2IwFvcRjrwfK0tybqB6mcz6NfxNPqZ82z+Vu2XVm
+XD+ORRNRmLLMYtFTP0XnTB/5A4OrjKEKBdfS+1ooisLBOi1UeQ/VIqcThrlJze2
vnWzV++wX1Ro9M8KyG4QbUKpk9R3ljNjiDh4i9jk36iHAaBWoMzkRaD+cN5SZf4c
fleFEG98JlOsRu2Kn2KBQcPX4uLD5nFvL9yk6SsHQQKBgQD7vn/zDkC8Ueis0pmL
/FTJqq6ypWTTQ+8At2Uavd2kWLOsAC4rgVI8r+Cs4iibkRyhnpl56U2AECU3ofCk
xFU5trL/s3DREGneA8KkUf+p6QIwDT6tMlT/pQuuz9yKsQPodqtxqoQMV0p1YXIg
A3WZzudHNQASaznf/dceSB7foQKBgQDfjwVFO2gcDch7rAjBh09AIXEsNDQCoiy/
JUQ98xuFWqaP0lRItZFtLcRJWOPgvll8PE65qiPUhawMVig2dDKmikEf4R61DHLZ
L3sYSWh1JOYCblyJmMk5PQxKdBqWZWWs7PiXYTX/wq0akofrZxWq9I8njGGPgeg5
SOae1a0kMwKBgQCnLNWJEeD5bidmhSBEbtfbaEZFCkKPbWCNCDzS6l0Co4kFYsVG
TMXQ2TcJd9JhpJbv2QOwirbVoWMls5u7v0mdXu81kPMNUqoLLlIWjwGJ0tuKD3Gc
0HzTm8XLW+voCi8/M3ccr5CrJVij5IdGLSXucxDxH4ghsyUm00oEqP4foQKBgQDP
Vqf+s8A09JuSB9X/F21q/xkldC0gnCSACyIliollvtNn5ByDatI7vgykMir2z9PS
o2QoUiH1Axy0PFwDVPV8/BC2bmW6aJdD0wOJXNvieZxReOWeP/OwgGwbyV63Scdp
AEb2rxQT5wwA7xHcQ7kW2sbCWTJKlKM6LeCmQ2rXfQKBgQDSDnTGMLsc3/K/A5xn
8YfZ3XZclR6hozjy9/HKQuTsmhLeRJNIlbbe19nfP46qQG+u8tslk22uGFN89Dms
3cJzwxPY+lO19eTV/fL9neit97KtevkgpOtGlWeV4GDAC/jsUziCX35VugJXsbPO
XNmuwuk/vK4GJ3qFO46q+ukzHg==
-----END PRIVATE KEY-----"""
client_email = "sheets-scraper@list-create-tool.iam.gserviceaccount.com"
client_id = "114480304124452371743"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-scraper%40list-create-tool.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
